version: 0.9.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: Directory.Build.props
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: Cachetwo\bin\Release\*.nupkg
- path: Cachetwo\bin\Release\netstandard2.0\*.*
